name: Trevas JS CI
on: [push]
jobs:
  test-build:
    name: Test & build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: yarn
      - run: yarn build
      - run: yarn test --coverage
      - run: yarn build-storybook
      - run: mkdir -p deploy/storybook
      - run: cp -R ./built-storybook/storybook/. ./deploy/storybook
      - run: yarn analyze
      - run: mkdir -p deploy/bundle-report
      - run: cp -a ./packages/vtl-2.0-antlr-tools/bundle-report/. ./deploy/bundle-report
      - run: cp -a ./packages/trevas/bundle-report/. ./deploy/bundle-report
  build-docs:
    name: Build docs
    # if: github.ref == 'refs/heads/main'
    needs: test-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          npm i -g gitbook-cli
          gitbook install
          gitbook build
        working-directory: ./docs
      - run: cp ./docs/_book/ ./deploy/
  deploy:
    # if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: deploy # The folder the action should deploy.
